version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            ./gradlew test
      - run:
          name: Sonar Scanner
          command: |
            ./gradlew sonarqube -PsystemProp.sonar.login=${SONAR_LOGIN}

workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: master
