/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wdstar.java.cli;

import org.junit.Test;
import static org.junit.Assert.*;

public class ExampleTest {
    @Test public void testExampleHasAGreeting() {
        Example classUnderTest = new Example();
        assertNotNull("Example should have a greeting", classUnderTest.getGreeting());
    }
}
