/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wdstar.java.cli;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.notNullValue;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;

import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
//import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest({ Example.class })
class ExampleTest {

	@Test
	void testExampleHasAGreeting() {
		Example example = new Example();
		String greeting = example.getGreeting();

		// by JUnit (traditional)
		assertNotNull(greeting);
		assertThat(greeting, notNullValue());
		// by AssertJ
		assertThat(greeting).isNotNull().startsWith("Hello world. Java: ");
	}

	@Test
	void testMain() {
		Example.main(new String[] {});
	}

}
