/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wdstar.java.cli;

import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;
import static org.assertj.core.api.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest({Example.class})
public class ExampleTest {
    @Test
    public void testExampleHasAGreeting() {
        Example example = new Example();
        String greeting = example.getGreeting();

        // by JUnit (traditional)
        assertNotNull(greeting);
        assertThat(greeting, notNullValue());
        // by AssertJ
        assertThat(greeting).isNotNull();
    }

    @Test
    public void testMain() {
        Example.main(new String[]{});
    }
}
