/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wdstar.java.cli;

import java.lang.invoke.MethodHandles;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Example {
    private static final Logger logger = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

    public String getGreeting() {
        return String.format("Hello world. Java: %s", System.getProperty("java.version"));
    }

    public static void main(String[] args) {
        logger.info("Greeting: " + new Example().getGreeting());

        logger.debug("debug message.");
        logger.info("info message");
        logger.warn("warn message");
        logger.error("error message");
    }
}
