/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wdstar.java.cli;

import static java.lang.String.format;

import java.lang.invoke.MethodHandles;

import com.github.wdstar.animals.Animal;
import com.github.wdstar.animals.Cat;
import com.github.wdstar.animals.Thing;
import com.github.wdstar.lombok.Person;

import org.apache.commons.lang3.SystemUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Example {

	private static final Logger logger = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

	public String getGreeting() {
		return format("Hello world. Java: %s", SystemUtils.JAVA_VERSION);
	}

	public static void main(String[] args) {
		logger.info("Greeting: {}", new Example().getGreeting());

		logger.debug("debug message.");
		logger.info("info message");
		logger.warn("warn message");
		logger.error("error message");

		logger.info(Animal.getInfo());
		Animal cat = new Cat();
		logger.info(cat.cry());
		Animal thing = new Thing();
		logger.info(thing.cry());

		Person alice = new Person();
		alice.setName("alice");
		alice.setAge(7);
		logger.info(alice.toString());
	}

}
